version: '3'

services:
  ldap:
    build:
      context: './'
      dockerfile: './Dockerfile-ldap'
    image: 'f9teams/zmc-ldap'
    volumes:
      - ~/src/:/src/
    domainname: 'f9teams.engineering'
    hostname: 'zmc-ldap'
    networks:
      default:
        ipv4_address: '10.0.0.2'
    ports:
      - '7389:389'
      - '7000:5000'
  mta:
    build:
      context: './'
      dockerfile: './Dockerfile-mta'
    image: 'f9teams/zmc-mta'
    volumes:
      - ~/src/:/src/
    domainname: 'f9teams.engineering'
    hostname: 'zmc-mta'
    networks:
      default:
        ipv4_address: '10.0.0.3'
    ports:
      - '6000:5000'
  mailbox:
    build:
      context: './'
      dockerfile: './Dockerfile-mailbox'
    image: 'f9teams/zmc-mailbox'
    volumes:
      - ~/src/:/src/
    domainname: 'f9teams.engineering'
    hostname: 'zmc-mailbox'
    networks:
      default:
        ipv4_address: '10.0.0.4'
    ports:
      - '9080:8080'
      - '9443:8443'
      - '9071:7071'
      - '9000:5000'
  mysql:
    build:
      context: './'
      dockerfile: './Dockerfile-mysql'
    image: 'f9teams/zmc-mysql'
    volumes:
      - ~/src/:/src/
    domainname: 'f9teams.engineering'
    hostname: 'zmc-mysql'
    networks:
      default:
        ipv4_address: '10.0.0.10'
    ports:
      - '10000:5000'
  proxy:
    build:
      context: './'
      dockerfile: './Dockerfile-proxy'
    image: 'f9teams/zmc-proxy'
    volumes:
      - ~/src/:/src/
    domainname: 'f9teams.engineering'
    hostname: 'zmc-proxy'
    networks:
      default:
        ipv4_address: '10.0.0.5'
    ports:
      - '8080:80'
      - '8443:443'
      - '8071:7071'
      - '8000:5000'
  solr1:
    image: solr:6.2-alpine
    ports:
      - "8983:8983"
    links:
      - zookeeper
    command: bash -c '/opt/solr/bin/solr start -f -z zookeeper:2181'
  solr2:
    image: solr:6.2-alpine
    links:
      - zookeeper
      - solr1
    command: bash -c '/opt/solr/bin/solr start -f -z zookeeper:2181'
  solr3:
    image: solr:6.2-alpine
    links:
      - zookeeper
      - solr1
      - solr2
    command: bash -c '/opt/solr/bin/solr start -f -z zookeeper:2181'
  zookeeper:
    image: jplock/zookeeper:3.4.8
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

networks:
  default:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '10.0.0.0/24'
