version: '3'

services:
  ldap:
    build:
      context: './'
      dockerfile: './ldap/Dockerfile'
    image: 'f9teams/zmc-ldap'
    volumes:
      - ~/src/:/src/
    hostname: zmc-ldap.f9teams.engineering
    networks:
      default:
        ipv4_address: '10.0.0.2'
    ports:
      - '7389:389'
      - '7000:5000'
  mta:
    build:
      context: './'
      dockerfile: './mta/Dockerfile'
    image: 'f9teams/zmc-mta'
    volumes:
      - ~/src/:/src/
    domainname: 'f9teams.engineering'
    hostname: 'zmc-mta'
    networks:
      default:
        ipv4_address: '10.0.0.3'
    ports:
      - '6000:5000'
  mailbox:
    build:
      context: './'
      dockerfile: './mailbox/Dockerfile'
    image: 'f9teams/zmc-mailbox'
    volumes:
      - ~/src/:/src/
    domainname: 'f9teams.engineering'
    hostname: 'zmc-mailbox'
    networks:
      default:
        ipv4_address: '10.0.0.4'
    ports:
      - '9080:8080'
      - '9443:8443'
      - '9071:7071'
      - '9000:5000'
  proxy:
    build:
      context: './'
      dockerfile: './proxy/Dockerfile'
    image: 'f9teams/zmc-proxy'
    volumes:
      - ~/src/:/src/
    domainname: 'f9teams.engineering'
    hostname: 'zmc-proxy'
    networks:
      default:
        ipv4_address: '10.0.0.5'
    ports:
      - '8080:80'
      - '8443:443'
      - '8071:7071'
      - '8000:5000'

networks:
  default:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '10.0.0.0/24'
