version: '3.3'

services:
  zmc-ldap:
    image: '${ZM_REPO_NS}/zmc-ldap:${ZM_TAG_NAME}'
    hostname: 'zmc-ldap'
    build:
      context: '.'
      dockerfile: 'ldap/Dockerfile'
      args:
         ZM_REPO_NS: '${ZM_REPO_NS}'
         ZM_TAG_NAME: '${ZM_TAG_NAME}'
    volumes:
      - .:/code
    configs:
      - domain_name
    secrets:
      - ca.key
      - ca.pem
      - ldap.key
      - ldap.crt
      - ldap.master_password
      - ldap.root_password
      - ldap.replication_password
      - ldap.postfix_password
      - ldap.amavis_password
      - ldap.nginx_password

  zmc-mta:
    image: '${ZM_REPO_NS}/zmc-mta:${ZM_TAG_NAME}'
    hostname: 'zmc-mta'
    build:
      context: '.'
      dockerfile: 'mta/Dockerfile'
      args:
         ZM_REPO_NS: '${ZM_REPO_NS}'
         ZM_TAG_NAME: '${ZM_TAG_NAME}'
    volumes:
      - .:/code
    configs:
      - av_notify_email
    secrets:
      - ca.key
      - ca.pem
      - mta.key
      - mta.crt
      - ldap.master_password
      - ldap.root_password
      - ldap.postfix_password
      - ldap.amavis_password

  zmc-mailbox:
    image: '${ZM_REPO_NS}/zmc-mailbox:${ZM_TAG_NAME}'
    hostname: 'zmc-mailbox'
    build:
      context: '.'
      dockerfile: 'mailbox/Dockerfile'
      args:
         ZM_REPO_NS: '${ZM_REPO_NS}'
         ZM_TAG_NAME: '${ZM_TAG_NAME}'
    volumes:
      - .:/code
      - blobvolume:/opt/zimbra/store
      - tmpvolume:/opt/zimbra/data/tmp
    configs:
      - domain_name
      - admin_account_name
      - spam_account_name
      - ham_account_name
      - virus_quarantine_account_name
      - gal_sync_account_name
    secrets:
      - ca.key
      - ca.pem
      - mailbox.key
      - mailbox.crt
      - ldap.master_password
      - ldap.root_password
      - mysql.password
      - admin_account_password
      - spam_account_password
      - ham_account_password
      - virus_quarantine_account_password

  zmc-mysql:
    image: '${ZM_REPO_NS}/zmc-mysql:${ZM_TAG_NAME}'
    hostname: 'zmc-mysql'
    build:
      context: '.'
      dockerfile: 'mysql/Dockerfile'
      args:
         ZM_REPO_NS: '${ZM_REPO_NS}'
         ZM_TAG_NAME: '${ZM_TAG_NAME}'
    volumes:
      - .:/code
    secrets:
      - mysql.password

  zmc-proxy:
    image: '${ZM_REPO_NS}/zmc-proxy:${ZM_TAG_NAME}'
    hostname: 'zmc-proxy'
    build:
      context: '.'
      dockerfile: 'proxy/Dockerfile'
      args:
         ZM_REPO_NS: '${ZM_REPO_NS}'
         ZM_TAG_NAME: '${ZM_TAG_NAME}'
    volumes:
      - .:/code
    secrets:
      - ca.key
      - ca.pem
      - proxy.key
      - proxy.crt
      - ldap.master_password
      - ldap.root_password
      - ldap.nginx_password
    ports:
      - '8080:80'
      - '8443:443'
      - '8071:7071'
      - '8000:5000'

secrets:
   ca.key:
     file: .keystore/ca.key
   ca.pem:
     file: .keystore/ca.pem
   ldap.key:
     file: .keystore/ldap.key
   ldap.crt:
     file: .keystore/ldap.crt
   mta.key:
     file: .keystore/mta.key
   mta.crt:
     file: .keystore/mta.crt
   mailbox.key:
     file: .keystore/mailbox.key
   mailbox.crt:
     file: .keystore/mailbox.crt
   proxy.key:
     file: .keystore/proxy.key
   proxy.crt:
     file: .keystore/proxy.crt
   ldap.master_password:
     file: .secrets/ldap.master_password
   ldap.root_password:
     file: .secrets/ldap.root_password
   ldap.replication_password:
     file: .secrets/ldap.replication_password
   ldap.postfix_password:
     file: .secrets/ldap.postfix_password
   ldap.amavis_password:
     file: .secrets/ldap.amavis_password
   ldap.nginx_password:
     file: .secrets/ldap.nginx_password
   mysql.password:
     file: .secrets/mysql.password
   admin_account_password:
     file: .secrets/admin_account_password
   spam_account_password:
     file: .secrets/spam_account_password
   ham_account_password:
     file: .secrets/ham_account_password
   virus_quarantine_account_password:
     file: .secrets/virus_quarantine_account_password

configs:
   av_notify_email:
     file: .config/av_notify_email
   domain_name:
     file: .config/domain_name
   admin_account_name:
     file: .config/admin_account_name
   spam_account_name:
     file: .config/spam_account_name
   ham_account_name:
     file: .config/ham_account_name
   virus_quarantine_account_name:
     file: .config/virus_quarantine_account_name
   gal_sync_account_name:
     file: .config/gal_sync_account_name

volumes:
  blobvolume: {}
  tmpvolume: {}
