version: '3'

services:
  zmc-ldap:
    image: 'zimbra/zmc-ldap'
    hostname: 'zmc-ldap'
    build:
      context: './ldap'
    volumes:
      - .:/code

  zmc-mta:
    image: 'zimbra/zmc-mta'
    hostname: 'zmc-mta'
    build:
      context: './mta'
    volumes:
      - .:/code

  zmc-mailbox:
    image: 'zimbra/zmc-mailbox'
    hostname: 'zmc-mailbox'
    build:
      context: './mailbox'
    volumes:
      - .:/code
      - blobvolume:/opt/zimbra/store
      - tmpvolume:/opt/zimbra/data/tmp

  zmc-mysql:
    image: 'zimbra/zmc-mysql'
    hostname: 'zmc-mysql'
    build:
      context: './mysql'
    volumes:
      - .:/code

  zmc-proxy:
    image: 'zimbra/zmc-proxy'
    hostname: 'zmc-proxy'
    build:
      context: './proxy'
    volumes:
      - .:/code
    ports:
      - '8080:80'
      - '8443:443'
      - '8071:7071'
      - '8000:5000'

  zmc-nginx:
    image: nginx
    hostname: 'zmc-nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '9080:8080'
      - '9443:8443'
      - '9071:7071'
      - '9000:5000'

volumes:
  blobvolume: {}
  tmpvolume: {}
