version: '3'

services:
  ldap:
    build:
      context: './ldap'
    image: 'zimbra/zmc-ldap'
    volumes:
      - ~/src/:/src/
    hostname: 'zmc-ldap'
    networks:
      default:
        aliases:
          - 'zmc-ldap'
        ipv4_address: '10.0.0.2'
    ports:
      - '7389:389'
      - '7000:5000'
  mta:
    build:
      context: './mta'
    image: 'zimbra/zmc-mta'
    volumes:
      - ~/src/:/src/
    hostname: 'zmc-mta'
    networks:
      default:
        aliases:
          - 'zmc-mta'
        ipv4_address: '10.0.0.3'
    ports:
      - '6000:5000'
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    hostname: 'zmc-mailbox'
    networks:
      default:
        aliases:
          - 'zmc-mailbox'
        ipv4_address: '10.0.0.4'
    ports:
      - '9080:8080'
      - '9443:8443'
      - '9071:7071'
      - '9000:5000'
  mailbox1:
    build:
      context: './mailbox'
    image: 'zimbra/zmc-mailbox'
    volumes:
      - ~/src/:/src/
      - blobvolume:/opt/zimbra/store
      - tmpvolume:/opt/zimbra/data/tmp
    hostname: 'zmc-mailbox'
    networks:
      default:
        ipv4_address: '10.0.0.14'
  mailbox2:
    build:
      context: './mailbox'
    image: 'zimbra/zmc-mailbox'
    volumes:
      - ~/src/:/src/
      - blobvolume:/opt/zimbra/store
      - tmpvolume:/opt/zimbra/data/tmp
    hostname: 'zmc-mailbox'
    networks:
      default:
        ipv4_address: '10.0.0.15'
  mysql:
    build:
      context: './mysql'
    image: 'zimbra/zmc-mysql'
    volumes:
      - ~/src/:/src/
    hostname: 'zmc-mysql'
    networks:
      default:
        aliases:
          - 'zmc-mysql'
        ipv4_address: '10.0.0.10'
    ports:
      - '10000:5000'
  proxy:
    build:
      context: './proxy'
    image: 'zimbra/zmc-proxy'
    volumes:
      - ~/src/:/src/
    hostname: 'zmc-proxy'
    networks:
      default:
        ipv4_address: '10.0.0.5'
    ports:
      - '8080:80'
      - '8443:443'
      - '8071:7071'
      - '8000:5000'
volumes:
  blobvolume: {}
  tmpvolume: {}

networks:
  default:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '10.0.0.0/24'
