version: 2
jobs:
  build:
    working_directory: /zmc-docker
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker-compose build
