version: 2
jobs:
  build:
    working_directory: /zmc-docker
    docker:
      - image: docker:17.05.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run: Install compose
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - run: Build containers
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker-compose build
