version: 2
jobs:
  build:
    working_directory: /zmc-docker
    docker:
      - image: docker:17.05.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install compose
          command: |
            set -x
            apk add --update py-pip
            pip install docker-compose
      - run:
          name: Build containers
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker-compose build --no-cache
      - run:
          name: Test containers
          command: |
            docker-compose up -d

            n=60
            status=0
            while [ $n -gt 0 ] && [ $status -ne 200 ]; do
              curl -k --silent --output /dev/null --write-out "%{http_code}" https://localhost:8443/ && break

              n=$[$n+1]
              sleep 10
            end

