version: '3.3'

services:
  zmc-account:
    image: 'zmc-account:latest'
    hostname: 'zmc-account'
    volumes:
      - ./src:/app/src
    entrypoint:
      - /app/init
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - "5000:5000"