version: '3'

services:
  bind:
    image: quay.io/sameersbn/bind
    volumes:
      - ./bind/:/data/bind/etc
    environment:
      WEBMIN_ENABLED: 'false'
    hostname: ns1.f9.engineering
    networks:
      zm-dev:
        ipv4_address: 12.0.0.255

  ldap:
    build: ./ldap
    depends_on:
      - bind
    dns:
      - 12.0.0.255
    hostname: ldap.f9.engineering
    volumes:
      - ./ldap:/zimbra
    networks:
      zm-dev:
        ipv4_address: 12.0.0.2

  mailbox:
    build: .
    depends_on:
      - bind
    dns:
      - 12.0.0.255
    hostname: ldap.f9.engineering
    volumes:
      - ./mailbox:/zimbra
    command: /zimbra/mailbox-entrypoint.sh
    healthcheck:
      test: 'if [ -e /opt/zimbra-installed ]; then; exit 0; else; exit 1; fi'
      interval: 30s
      retries: 50
    networks:
      - zm-dev

networks:
  zm-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 12.0.0.0/16
